### ISSUE TITLE
WASM API allows transfer cancellation

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/wormhole-william#22]
Acceptance Criteria:
- [ ] API consumers are able to cancel a pending file transfers (sending)
- [ ] API consumers are able to cancel a pending file transfers (receiving)

**Comment by donpui** [comment]
Currently we have option to cancel from Wasm part, however there are multiple issues, like https://github.com/LeastAuthority/winden/issues/83 or in internal OpenProject. Biggest challange, that we don't have proper way how to notify a peer, that we cancelled on certain cases. Pair usually sees this as network, data stream interruption.
