### ISSUE TITLE
Initial C client API

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/wormhole-william#23]
## Acceptance Criteria:

- C functions return a numeric status code
  - An exception can be made for wrapping go functions which don't return an error (e.g. constructors)
- Go functions returning go objects to which a reference is needed should hold such references in a go map and pass the map index back to C for use later
- API includes members to:
  - Create a new client (e.g. NewClient)
  - Garbage collect a client (e.g. FreeClient)
  - Send a file (e.g. Client_SendFile)
  - Receive a file (e.g. Client_ReceiveFile)

**Comment by donpui** [comment]
We already have and it is used with Destiny
