### ISSUE TITLE
Relay upgrade | websockets support

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/wormhole-william#3]
As we intend to use this client library in the browser, we require that it (and its dependencies) be compatible with go's WASM support. In the [spike](https://github.com/LeastAuthority/wormhole-william/pull/1) we learned that we may need to do some refactoring to support multiple transports. The WASM build only needs to support the websocket transport but normal builds need to support **both**.

**Comment by vu3rdd** [comment]
In the current commandline wormhole applications, the user passes the relay address to wormhole-william via a command line switch/flag and the url is typically `tcp:transit.magic-wormhole.io:4001` (i.e. it is of the form `protocol:hostname:port`).

Each client sends direct hints and/or relay hints to each other via the established wormhole mailbox. The relay hint is of the form:

```
{
  "type": "relay-v1",
  "hints": [
      { 
        "hostname": "foo.bar.baz",
        "priority": 0.5,
        "type":"direct-tcp-v1",
        "port":1234
      }]
}
```
i.e. The outer type of the hint is "`relay-v1`" and it gives a list of hints and each of them also have a type.

Perhaps we should introduce a new "`direct-websocket-v1`" type to indicate a websocket capable host and port. Same server can expose both tcp and websocket and this can be used by having multiple entries in the list for the same host with different type and port and priority fields. The clients can use the type information to talk the right protocol to the server for connection establishment.

**Comment by vu3rdd** [comment]
Also, there is a simple [test transit relay](https://github.com/LeastAuthority/wormhole-william/blob/master/wormhole/wormhole_test.go#L455_L592) in the tests. Once the handshake is done, they just talk the regular file transfer protocol, so the test transit relay implementation is really simple and can be reused easily (it currently listens on a tcp port, but with some simple changes, can be made to listen for websocket connections).

**Comment by vu3rdd** [comment]
The `wasm-compat` branch has the websocket client implementation that tests against a test websocket relay server.

There are a few short cuts that I had to take. Also the upstream code also needs some refactoring. Websocket addresses are really URLs, not (host, port) pairs. So, that does not fit into the model followed by magic-wormhole's hint data structure. This needs to be fixed. Thankfully, hints have a versioning system, so we could create another version without disturbing existing structures and still be compatible.

**Comment by donpui** [comment]
Old issue, not actual anymore, we already have websocket support
