### ISSUE TITLE
sender and recipient should both be listening for incoming connections while concurrently trying to connect to the peer

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/wormhole-william#50]
In a true peer to peer system, the two parties are both a network server and a client. But in the file transfer mode with direct connections, wormhole william sender is listening and recipient is always dialing. In the canonical python implementation, both sender and recipient are listening and dialing into each direct and relay hint concurrently and use the first connection that succeed.

**Comment by piegamesde** [comment]
Upstream tracks this here: https://github.com/psanford/wormhole-william/issues/57

**Comment by donpui** [comment]
Dublicate of #25
