### ISSUE TITLE
Receive progress

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/wormhole-william#8]
It seems like the right thing to do here would be to implement something analogous to [`WithProgress`](https://github.com/LeastAuthority/wormhole-william/blob/master/wormhole/send.go#L677) from send.go. 

I see that [`IncomingMessage`](https://github.com/LeastAuthority/wormhole-william/blob/master/wormhole/recv.go#L322) is keeping an accurate count of how much data has come through so that seems like good place to start. This will need to be exposed to the JS API.
_(NOTE: I expect that we should be able to use the same structs/interface with both send and receive)_

**Comment by donpui** [comment]
Old issue, we already have progress in Winden JS frontend.
