### ISSUE TITLE
default relay url never gets used

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/wormhole-william#89]
The code in https://github.com/LeastAuthority/wormhole-william/blob/master/wormhole/file_transport.go#L275_L278 has a bug. If `relayUrl` is `nil` then we shouldn't be destructuring and assigning values to it. That would lead to a crash.

A simple fix could be:
```
	if relayUrl == nil {
		relayUrl = t.relayURL
	}
```
I guess this probably got introduced when we converted the code to use Go [net/url](https://pkg.go.dev/net/url) library.

**Comment by piegamesde** [comment]
It got introduced in #84, and yes the semantics of this are wrong. Good catch!
